# Generated by Django 4.2.7 on 2025-09-19 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Comment text (supports Hindi and English)",
                        max_length=500,
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of likes on comment"
                    ),
                ),
                (
                    "replies_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of replies"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Comment has been edited"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Comment author",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="social.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post being commented on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "gupshup_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Liked post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "db_table": "gupshup_likes",
                "indexes": [
                    models.Index(
                        fields=["post", "-created_at"],
                        name="gupshup_lik_post_id_31cbea_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gupshup_lik_user_id_01fb27_idx",
                    ),
                ],
                "unique_together": {("user", "post")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Following"),
                            ("blocked", "Blocked"),
                        ],
                        default="accepted",
                        help_text="Follow request status",
                        max_length=10,
                    ),
                ),
                (
                    "is_mutual",
                    models.BooleanField(
                        default=False, help_text="Both users follow each other"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="User who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        help_text="User being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
                "db_table": "gupshup_follows",
                "indexes": [
                    models.Index(
                        fields=["follower", "status"],
                        name="gupshup_fol_followe_f1b852_idx",
                    ),
                    models.Index(
                        fields=["following", "status"],
                        name="gupshup_fol_followi_901a45_idx",
                    ),
                    models.Index(
                        fields=["is_mutual"], name="gupshup_fol_is_mutu_2c32ba_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="gupshup_fol_created_416a12_idx"
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        help_text="Liked comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="social.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who liked comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Like",
                "verbose_name_plural": "Comment Likes",
                "db_table": "gupshup_comment_likes",
                "indexes": [
                    models.Index(
                        fields=["comment", "-created_at"],
                        name="gupshup_com_comment_77d0ac_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gupshup_com_user_id_e5b20d_idx",
                    ),
                ],
                "unique_together": {("user", "comment")},
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "-created_at"], name="gupshup_com_post_id_51e455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at"], name="gupshup_com_author__75e904_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="gupshup_com_parent__90eae3_idx"
            ),
        ),
    ]
