# Generated by Django 4.2.7 on 2025-09-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_on_follow", models.BooleanField(default=True)),
                ("email_on_like", models.BooleanField(default=False)),
                ("email_on_comment", models.BooleanField(default=True)),
                ("email_on_message", models.BooleanField(default=True)),
                ("email_on_mention", models.BooleanField(default=True)),
                ("web_on_follow", models.BooleanField(default=True)),
                ("web_on_like", models.BooleanField(default=True)),
                ("web_on_comment", models.BooleanField(default=True)),
                ("web_on_message", models.BooleanField(default=True)),
                ("web_on_mention", models.BooleanField(default=True)),
                ("push_on_follow", models.BooleanField(default=False)),
                ("push_on_like", models.BooleanField(default=False)),
                ("push_on_comment", models.BooleanField(default=False)),
                ("push_on_message", models.BooleanField(default=True)),
                ("push_on_mention", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="No notifications after this time",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="No notifications before this time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notificationsetting",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("follow", "New Follower"),
                            ("follow_request", "Follow Request"),
                            ("follow_accepted", "Follow Request Accepted"),
                            ("like", "Post Liked"),
                            ("comment", "New Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("message", "New Message"),
                            ("mention", "Mentioned in Post"),
                            ("post_shared", "Post Shared"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("object_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="notificatio_notific_d8746a_idx",
                    ),
                ],
            },
        ),
    ]
